apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: grunn-og-hjelpestonad
    namespace: grunn-og-hjelp

spec:
    # Applikasjon konfigurasjon
    image: {{image}}
    port: 8080
    replicas:
        min: 2
        max: 2
    leaderElection: true
    kafka:
        pool: nav-dev
    resources:
        limits:
            memory: 1024Mi
        requests:
            cpu: 162m
            memory: 512Mi

    env:
        -   name: SPRING_PROFILES_ACTIVE
            value: dev
    gcp:
        sqlInstances:
            -   name: grunn-og-hjelpestonad
                type: POSTGRES_17
                tier: db-g1-small
                diskAutoresize: true
                cascadingDelete: false
                highAvailability: false
                pointInTimeRecovery: true
                maintenance:
                    day: 7
                    hour: 23
                databases:
                    -   name: grunn-og-hjelpestonad
                        envVarPrefix: DB

    # Nettverk
    ingresses:
        - https://grunn-og-hjelpestonad-backend.intern.dev.nav.no
    accessPolicy:
        inbound:
            rules:
                -   application: grunn-og-hjelpestonad-frontend
                -   application: grunn-og-hjelpestonad-frontend-lokal
                -   application: etterlatte-prosessering
        outbound:
            rules:
                -   application: grunn-og-hjelpestonad-frontend
                -   application: grunn-og-hjelpestonad-frontend-lokal
                -   application: populasjonstilgangskontroll
                    namespace: tilgangsmaskin
                -   application: familie-dokument
                    namespace: teamfamilie
                -   application: entra-proxy
                    namespace: sikkerhetstjenesten
                -   application: oppgave
                    namespace: oppgavehandtering
                    # Team Logs
                -   application: logging
                    namespace: nais-system
            external:
                -   host: grunn-og-hjelpestonad-infotrygd.dev-fss-pub.nais.io
                -   host: etterlatte-unleash-api.nav.cloud.nais.io
                -   host: familie-integrasjoner.dev-fss-pub.nais.io
                -   host: saf-q2.dev-fss-pub.nais.io
                -   host: dokarkiv-q2.dev-fss-pub.nais.io

    # Toggle
    envFrom:
        -   secret: grunn-og-hjelpestonad

    # Helse
    liveness:
        path: /internal/health/liveness
        initialDelay: 30
        failureThreshold: 10
    readiness:
        path: /internal/health/readiness
        initialDelay: 30
        failureThreshold: 10

    # Logging
    prometheus:
        enabled: true
        path: /internal/prometheus
    observability:
        autoInstrumentation:
            enabled: true
            runtime: java
        logging:
            destinations:
                -   id: loki
                -   id: elastic

    # Autentisering
    azure:
        application:
            enabled: true
            tenant: trygdeetaten.no
            claims:
                groups:
                    - id: 7ce9d1d2-d149-4324-832b-8d459762a102 # Saksbehandler
                    - id: 84c4a287-abd6-46c1-bf93-dbf90f1a326d # Beslutter
                    - id: a181921e-2a55-4198-896b-0086cc805278 # Lesetilgang
                extra:
                    - "NAVident"
                    - "azp_name"
            replyURLs:
                - https://grunn-og-hjelpestonad-backend.intern.dev.nav.no/swagger-ui/oauth2-redirect.html
            singlePageApplication: true
