# Unleash API Token
# Denne trenger kun å deployes en gang per endring
# For å deploye kan Nais dev yaml kan utvides:
#       RESOURCE: .nais/dev.yaml, .nais/unleash-apitoken.yaml

apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
    name: grunn-og-hjelpestonad
    namespace: grunn-og-hjelp
    labels:
        team: grunn-og-hjelp
spec:
    unleashInstance:
        apiVersion: unleash.nais.io/v1
        kind: RemoteUnleash
        name: grunn-og-hjelp
    secretName: grunn-og-hjelpestonad-unleash-api-token

    # Specify which environment the API token should be created for.
    # Can be one of: development, or production.
    environment: development
