apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: utbetaling-bs.v1
    namespace: grunn-og-hjelp
    labels:
        team: grunn-og-hjelp
spec:
    pool: nav-dev
    config:
        cleanupPolicy: delete
        minimumInSyncReplicas: 2
        partitions: 1
        replication: 3
        retentionBytes: -1
        retentionHours: 720
    acl:
        -   team: grunn-og-hjelp
            application: grunn-og-hjelpestonad
            access: readwrite
        -   team: helved
            application: peisschtappern
            access: read
        -   team: helved
            application: abetal
            access: read
