-- Tabellene som replikeres fra Exodus (se ExodusTabell). Kolonner, nullbarhet og primærnøkler
-- følger kildetabellene i Oracle. NUMBER blir bigint, bortsett fra beløp med desimaler, som blir
-- numeric. DATE blir date og TIMESTAMP(6) blir timestamp. CHAR og VARCHAR2 blir text, siden
-- ExodusUpsertRepository fjerner utfylling med mellomrom fra Oracle CHAR før lagring.

create table ev_data_10 (
    ev01_personkey    bigint not null,
    ev05_aar_mnd_seq  text not null,
    ev10_ps_type      text not null,
    ev10_posisjon     text not null,
    ev10_antall_pos   text not null,
    ev10_belop        text not null,
    ev10_mottatt_dato bigint not null,
    ev10_text         text not null,
    ev10_des_kode     text not null,
    ev10_vedtaks_dag  text not null,
    tk_nr             text not null,
    f_nr              text not null,
    opprettet         timestamp not null,
    endret_i_kilde    timestamp not null,
    kilde_is          text not null,
    region            text not null,
    id_ev_10          bigint not null,
    oppdatert         timestamp not null,
    db_splitt         text not null,
    db_splitt_concat  text,
    primary key (id_ev_10)
);

create table ev_valg_05 (
    ev01_personkey   bigint not null,
    ev05_aar_mnd_seq text not null,
    ev05_kap         text not null,
    ev05_valg        text not null,
    ev05_uvalg       text not null,
    ev05_type        text not null,
    ev05_ir          text not null,
    ev05_ir_verdi    text not null,
    ev05_nivaa       text not null,
    ev05_tekst_kode  text not null,
    ev05_sak         text not null,
    ev05_i_verdi     text not null,
    tk_nr            text not null,
    f_nr             text not null,
    opprettet        timestamp not null,
    endret_i_kilde   timestamp not null,
    kilde_is         text not null,
    region           text not null,
    id_ev_05         bigint not null,
    oppdatert        timestamp not null,
    db_splitt        text not null,
    primary key (id_ev_05)
);

create table sa_hendelse_20 (
    s01_personkey       bigint not null,
    s05_saksblokk       text not null,
    s20_aksjonsdato_seq bigint not null,
    s20_s_b_kode        text not null,
    s20_brevnummer      text not null,
    s20_mottakerkode    text not null,
    s20_mottakernr      text not null,
    s20_fnr_anr_instnr  bigint not null,
    s20_opplysning      text not null,
    s20_ant_purreuker_1 text not null,
    s20_ant_purreuker_2 text not null,
    s20_ant_purreuker_3 text not null,
    s20_s_purrenr       text not null,
    s20_1_purredato     bigint not null,
    s20_2_purredato     bigint not null,
    s20_3_purredato     bigint not null,
    s20_returdato       bigint not null,
    s20_neste_purredato bigint not null,
    s20_saksnr          text not null,
    s20_kladd           text not null,
    s20_lopenr_fm01     text not null,
    s20_lopenr_print    text not null,
    s20_sentralprint    text not null,
    s20_brevtype        text not null,
    s20_tekstkode_1     text not null,
    s20_tekstkode_2     text not null,
    s20_tekstkode_3     text not null,
    s20_tekstkode_4     text not null,
    s20_tekstkode_5     text not null,
    s20_purretekst_1    text not null,
    s20_purretekst_2    text not null,
    s20_purretekst_3    text not null,
    s20_dato_dannet     bigint not null,
    s20_lager           text not null,
    s20_reg_av          text not null,
    s20_oppr_tknr       text not null,
    s20_oppr_brukerid   text not null,
    s20_ikke_avbryt     text not null,
    s20_maalform        text not null,
    tk_nr               text not null,
    f_nr                text not null,
    opprettet           timestamp not null,
    endret_i_kilde      timestamp not null,
    kilde_is            text not null,
    region              text not null,
    id_hend             bigint not null,
    oppdatert           timestamp not null,
    db_splitt           text not null,
    primary key (id_hend)
);

create table sa_sak_10 (
    s01_personkey          bigint not null,
    s05_saksblokk          text not null,
    s10_saksnr             text not null,
    s10_reg_dato           bigint not null,
    s10_mottattdato        bigint not null,
    s10_kapittelnr         text not null,
    s10_valg               text not null,
    s10_undervalg          text not null,
    s10_dublett_feil       text not null,
    s10_type               text not null,
    s10_innstilling        text not null,
    s10_resultat           text not null,
    s10_nivaa              text not null,
    s10_innstilldato       bigint not null,
    s10_vedtaksdato        bigint not null,
    s10_iverksattdato      bigint not null,
    s10_grunnbl_dato       bigint not null,
    s10_aarsakskode        text not null,
    s10_tellepunkt         text not null,
    s10_telletype          text not null,
    s10_telledato          bigint not null,
    s10_eval_kode          text not null,
    s10_eval_tir           text not null,
    s10_fremlegg           text not null,
    s10_innstilling2       text not null,
    s10_innstilldato2      bigint not null,
    s10_annen_instans      text not null,
    s10_behen_type         text not null,
    s10_behen_enhet        text not null,
    s10_reg_av_type        text not null,
    s10_reg_av_enhet       text not null,
    s10_diff_framlegg      text not null,
    s10_innstillt_av_type  text not null,
    s10_innstillt_av_enhet text not null,
    s10_vedtatt_av_type    text not null,
    s10_vedtatt_av_enhet   text not null,
    s10_prio_tab           text not null,
    s10_aoe                text not null,
    s10_es_system          text not null,
    s10_es_gsak_oppdragsid bigint not null,
    s10_knyttet_til_sak    text not null,
    s10_vedtakstype        text not null,
    s10_reell_enhet        text not null,
    s10_mod_endret         text not null,
    tk_nr                  text not null,
    f_nr                   text not null,
    opprettet              timestamp not null,
    endret_i_kilde         timestamp not null,
    kilde_is               text not null,
    region                 text not null,
    id_sak                 bigint not null,
    oppdatert              timestamp not null,
    db_splitt              text not null,
    primary key (id_sak)
);

create table sa_status_15 (
    s01_personkey       bigint not null,
    s05_saksblokk       text not null,
    s10_saksnr          text not null,
    s15_lopenr          text not null,
    s15_beh_enhet_type  text not null,
    s15_beh_enhet_enhet text not null,
    s15_status          text not null,
    s15_status_dato     bigint not null,
    s15_brukerid        text not null,
    s15_status_klokke   text not null,
    s15_status_brukerid text not null,
    s15_endrings_kode   text not null,
    s15_type_gml        text not null,
    s15_type_ny         text not null,
    s15_lovetsvar_dato  bigint not null,
    s15_ant_lofter      text not null,
    s15_gruppe          text not null,
    s15_sperr           text not null,
    tk_nr               text not null,
    f_nr                text not null,
    opprettet           timestamp not null,
    endret_i_kilde      timestamp not null,
    kilde_is            text not null,
    region              text not null,
    id_status           bigint not null,
    oppdatert           timestamp not null,
    db_splitt           text not null,
    primary key (id_status)
);

create table t_avstemming (
    kode_rutine     text not null,
    type_avstemming text not null,
    avst_id         bigint not null,
    dato_kjort      date not null,
    brukerid        text not null,
    tidspunkt_reg   timestamp not null,
    opprettet       timestamp,
    oppdatert       timestamp,
    db_splitt       text,
    primary key (kode_rutine, type_avstemming, avst_id)
);

create table t_delytelse (
    vedtak_id       bigint not null,
    type_delytelse  text not null,
    tidspunkt_reg   timestamp not null,
    fom             date not null,
    tom             date,
    belop           numeric(11, 2) not null,
    oppgjorsordning text,
    mottaker_lopenr bigint,
    brukerid        text not null,
    type_sats       text not null,
    type_utbetaling text not null,
    linje_id        bigint,
    opprettet       timestamp,
    oppdatert       timestamp,
    db_splitt       text,
    primary key (vedtak_id, type_delytelse, tidspunkt_reg)
);

create table t_endring (
    vedtak_id bigint not null,
    kode      text not null,
    opprettet timestamp,
    oppdatert timestamp,
    db_splitt text,
    primary key (vedtak_id, kode)
);

create table t_gh (
    vedtak_id      bigint not null,
    tidspunkt_reg  timestamp not null,
    trygdetid      bigint not null,
    sats_gs        bigint,
    sats_hs        bigint,
    brukerid       text not null,
    opprettet      timestamp,
    oppdatert      timestamp,
    db_splitt      text,
    endret_i_kilde timestamp not null,
    primary key (vedtak_id, tidspunkt_reg)
);

create table t_lopenr_fnr (
    person_lopenr bigint not null,
    personnr      text not null,
    opprettet     timestamp,
    oppdatert     timestamp,
    db_splitt     text,
    primary key (person_lopenr)
);

create table t_stonad (
    stonad_id         bigint not null,
    person_lopenr     bigint not null,
    kode_rutine       text not null,
    dato_start        date not null,
    kode_opphor       text,
    dato_opphor       date,
    oppdrag_id        bigint,
    tidspunkt_opphort timestamp,
    tidspunkt_reg     timestamp,
    brukerid          text,
    opprettet         timestamp,
    oppdatert         timestamp,
    db_splitt         text,
    primary key (stonad_id)
);

create table t_vedtak (
    vedtak_id           bigint not null,
    person_lopenr       bigint not null,
    kode_rutine         text not null,
    dato_start          date not null,
    tknr                text not null,
    saksblokk           text not null,
    saksnr              bigint not null,
    type_sak            text not null,
    kode_resultat       text not null,
    dato_innv_fom       date not null,
    dato_innv_tom       date,
    dato_mottatt_sak    date not null,
    kode_vedtaksnivaa   text not null,
    type_beregning      text not null,
    tknr_beh            text not null,
    tidspunkt_reg       timestamp not null,
    brukerid            text not null,
    nokkel_dl1          text,
    alternativ_mottaker bigint,
    stonad_id           bigint not null,
    kidnr               text,
    faktnr              text,
    opprettet           timestamp,
    oppdatert           timestamp,
    db_splitt           text,
    primary key (vedtak_id)
);

create index idx_t_lopenr_fnr_personnr on t_lopenr_fnr (personnr);
create index idx_t_stonad_person_lopenr on t_stonad (person_lopenr);
create index idx_t_vedtak_stonad_id on t_vedtak (stonad_id);
create index idx_sa_sak_10_f_nr on sa_sak_10 (f_nr);
