server.port: 8080

spring:
  application:
    name: grunn-og-hjelp-infotrygd
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  datasource:
      url: ${DB_JDBC_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
          maximum-pool-size: 20
          connection-test-query: "select 1"
          max-lifetime: 90000
          minimum-idle: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
      base-path: /internal

no.nav.security.jwt:
  expirythreshold: 60 #threshold in minutes until token expires
  issuer:
    azure:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: ${APP_AZURE_PROXY_URL}
