server.port: 8080

spring:
  application:
    name: grunn-og-hjelp-infotrygd
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  datasource:
      url: ${DB_JDBC_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
          maximum-pool-size: 20
          connection-test-query: "select 1"
          max-lifetime: 90000
          minimum-idle: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}
  flyway:
    enabled: true
    locations: classpath:db/migration

nais:
  texas:
    token-endpoint: ${NAIS_TOKEN_ENDPOINT}

exodus:
  base-url: ${EXODUS_BASE_URL}
  scope: ${EXODUS_SCOPE}
  batch-storrelse: 1000
  scheduler-cron: "0 */5 * * * *"
  maks-sider-per-kjoring: 500
  scheduler-enabled: ${EXODUS_SCHEDULER_ENABLED:false}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
      base-path: /internal

azure:
  app:
    tenant:
      id: ${AZURE_APP_TENANT_ID}
    client:
      id: ${AZURE_APP_CLIENT_ID}
  authorization-url: https://login.microsoftonline.com/${azure.app.tenant.id}/oauth2/v2.0/authorize
  token-endpoint-url: https://login.microsoftonline.com/${azure.app.tenant.id}/oauth2/v2.0/token
  api-scope: api://${azure.app.client.id}/.default

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    disable-swagger-default-url: true
    persist-authorization: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${azure.app.client.id}
      scope-separator: ","

no.nav.security.jwt:
  expirythreshold: 60 #threshold in minutes until token expires
  issuer:
    azure:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: ${APP_AZURE_PROXY_URL}
