apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: grunn-og-hjelp-infotrygd
    namespace: grunn-og-hjelp

spec:
    # Applikasjon konfigurasjon
    image: {{ image }}
    port: 8080
    replicas:
        min: 1
        max: 2
    resources:
        requests:
            cpu: 20m
            memory: 256Mi
        limits:
            memory: 512Mi
    gcp:
        sqlInstances:
            -   name: grunn-og-hjelp-infotrygd
                type: POSTGRES_18
                tier: db-g1-small
                diskAutoresize: true
                cascadingDelete: false
                highAvailability: false
                pointInTimeRecovery: true
                maintenance:
                    day: 7
                    hour: 23
                databases:
                    -   name: grunn-og-hjelp-infotrygd
                        envVarPrefix: DB

    # Nettverk
    ingresses:
        - https://grunn-og-hjelp-infotrygd.intern.dev.nav.no
    accessPolicy:
        inbound:
            rules:
                -   application: grunn-og-hjelpestonad
                    cluster: dev-gcp
        outbound:
            rules:
                -   application: grunn-og-hjelpestonad
                    namespace: grunn-og-hjelp
                    cluster: dev-gcp
                -   application: grunn-og-hjelp-exodus
                    namespace: grunn-og-hjelp
                    cluster: dev-gcp

                    # Team logs
                -   application: logging
                    namespace: nais-system

    # Helse
    liveness:
        path: /internal/health/liveness
        initialDelay: 30
        failureThreshold: 10
    readiness:
        path: /internal/health/readiness
        initialDelay: 30
        failureThreshold: 10

    # Logging
    prometheus:
        enabled: true
        path: /internal/prometheus
    observability:
        autoInstrumentation:
            enabled: true
            runtime: java
        logging:
            destinations:
                -   id: loki
                -   id: elastic

    #Autentisering
    azure:
        application:
            enabled: true
            tenant: trygdeetaten.no
            claims:
                groups:
                    - id: 7ce9d1d2-d149-4324-832b-8d459762a102 # Saksbehandler
                    - id: 84c4a287-abd6-46c1-bf93-dbf90f1a326d # Beslutter
                    - id: a181921e-2a55-4198-896b-0086cc805278 # Lesetilgang
                extra:
                    - "NAVident"
                    - "azp_name"
            replyURLs:
                - https://grunn-og-hjelp-infotrygd.intern.dev.nav.no/swagger-ui/oauth2-redirect.html
            singlePageApplication: true
    env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: EXODUS_BASE_URL
          value: "https://grunn-og-hjelp-exodus.intern.dev.nav.no"
        - name: EXODUS_SCOPE
          value: "api://dev-gcp.grunn-og-hjelp.grunn-og-hjelp-exodus/.default"
        - name: EXODUS_SCHEDULER_ENABLED
          value: "true"
